
- name: Enable AUR for pamac
  replace:
    path: /etc/pamac.conf
    regexp: '^#EnableAUR$'
    replace: 'EnableAUR'
  become: yes

- name: Enable AUR updates for pamac
  replace:
    path: /etc/pamac.conf
    regexp: '^#CheckAURUpdates$'
    replace: 'CheckAURUpdates'
  become: yes

- name: Install minimal tools ...
  shell: pamac install --no-confirm tmux httpie jq
  become: yes

- name: Install minimal tools from AUR...
  shell: pamac build --no-confirm bash-git-prompt